apiVersion: v1
kind: Secret
metadata:
  name: slack-mcp-server-secrets
type: Opaque
stringData:
  # Add your slack bot token and slack workspace team id
  SLACK_BOT_TOKEN: "${SLACK_BOT_TOKEN}"
  SLACK_TEAM_ID: "${SLACK_TEAM_ID}"