apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rhai-agentic-demo

resources:
  - ../../llama-serve/llama3.2-3b
  - ../../llama-serve/granite3.2-8b
#  - ../../llama-serve/hpu-llama3.2-3b
#  - ../../llama-serve/hpu-granite3.2-8b
  - ../../llama-stack
  - ../../crm
  - ../../database
  - ../../ui
  - ../../mcp-servers/crm
  - ../../mcp-servers/slack
  - ../../mcp-servers/pdf
