apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../llama-serve/llama3.2-3b
  - ../../llama-serve/granite3.2-8b
  - ../../llama-stack
  - ../../mcp-servers/crm
  - ../../mcp-servers/slack
  #- ../../mcp-servers/pdf
  #- ../../mcp-servers/python