apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-mcp-server
  labels:
    app: upload-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-mcp-server
  template:
    metadata:
      labels:
        app: upload-mcp-server
    spec:
      containers:
      - name: upload-mcp-server
        image: quay.io/rh-aiservices-bu/mcp-servers:upload
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
        - |
          npx -y supergateway --stdio "node dist/index.js" --port 8080
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: NPM_CONFIG_CACHE
          value: /tmp/.npm
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"